//whew

exports.EffectMap = {
  "Nebula": 0,
  "Burning Flames": 1,
  "It's A Secret To Everybody": 2,
  "Spellbound": 3,
  "Scorching Flames": 4,
  "Harvest Moon": 5,
  "Sunbeams": 6,
  "Abduction": 7,
  "Arcana": 8,
  "Darkblaze": 9,
  "Cloudy Moon": 10,
  "Bonzo The All-Gnawing": 11,
  "Poisoned Shadows": 12,
  "Knifestorm": 13,
  "Roboactive": 14,
  "Chiroptera Venenata": 15,
  "Anti-Freeze": 16,
  "Misty Skull": 17,
  "Energy Orb": 18,
  "Hellfire": 19,
  "Stormy 13th Hour": 20,
  "Demonflame": 21,
  "Atomic": 22,
  "Purple Energy": 23,
  "Galactic Codex": 24,
  "Death by Disco": 25,
  "Something Burning This Way Comes": 26,
  "Voltaic Hat Protector": 27,
  "Subatomic": 28,
  "Ancient Codex": 29,
  "Ghastly Ghosts": 30,
  "Death at Dusk": 31,
  "Frostbite": 32,
  "Green Energy": 33,
  "Ether Trail": 34,
  "Time Warp": 35,
  "Cool": 36,
  "Morning Glory": 37,
  "Green Black Hole": 38,
  "Magnetic Hat Protector": 39,
  "Ghastly Ghosts Jr": 40,
  "Nether Trail": 41,
  "Amaranthine": 42,
  "Circling Heart": 43,
  "The Ooze": 44,
  "Sulphurous": 45,
  "Cauldron Bubbles": 46,
  "Electric Hat Protector": 47,
  "Eldritch Flame": 48,
  "Stare From Beyond": 49,
  "Ancient Eldritch": 50,
  "Haunted Ghosts": 51,
  "Haunted Phantasm Jr": 52,
  "It's a mystery to everyone": 53,
  "Haunted Phantasm": 54,
  "Phosphorous": 55,
  "It's a puzzle to me": 56,
  "Flaming Lantern": 57,
  "Hot": 58,
  "Isotope": 59,
  "Vivid Plasma": 60,
  "Molten Mallard": 61,
  "Tesla Coil": 62,
  "Power Surge": 63,
  "Holy Grail": 64,
  "Electrostatic": 65,
  "Starstorm Insomnia": 66,
  "Disco Beat Down": 67,
  "Searing Plasma": 68,
  "Eerie Orbiting Fire": 69,
  "Starstorm Slumber": 70,
  "Cloud 9": 71,
  "Circling Peace Sign": 72,
  "Screaming Tiger": 73,
  "Neutron Star": 74,
  "Internal Smoke": 75,
  "Circling TF Logo": 76,
  "Hellish Inferno": 77,
  "Purple Confetti": 78,
  "Stormy Storm": 79,
  "Spectral Swirl": 80,
  "Blizzardy Storm": 81,
  "Infernal Flames": 82,
  "Showstopper": 83,
  "Fountain of Delight": 84,
  "Miami Nights": 85,
  "Memory Leak": 86,
  "Green Confetti": 87,
  "'72": 88,
  "Terror-Watt": 89,
  "Orbiting-Fire": 90,
  "Orbiting Planets": 91,
  "Bubbling": 92,
  "Steaming": 93,
  "Smoking": 94,
  "Massed Flies": 95,
  "Kill-a-Watt": 96,
  "Overclocked": 97,
  "Dead Presidents": 98,
  "Aces High": 99,
  "Skill Gotten Gains": 100,
  "Nuts n' Bolts": 101,
  "Mega Strike": 102,
  "Silver Cyclone": 103,
  "Midnight Whirlwind": 104,
}
