//whew

exports.EffectMap = {
  "Nebula": ,
  "Burning Flames": ,
  "It's A Secret To Everybody": ,
  "Spellbound": ,
  "Scorching Flames": ,
  "Harvest Moon": ,
  "Sunbeams": ,
  "Abduction": ,
  "Arcana": ,
  "Darkblaze": ,
  "Cloudy Moon": ,
  "Bonzo The All-Gnawing": ,
  "Poisoned Shadows": ,
  "Knifestorm": ,
  "Roboactive": ,
  "Chiroptera Venenata": ,
  "Anti-Freeze": ,
  "Misty Skull": ,
  "Energy Orb": ,
  "Hellfire": ,
  "Stormy 13th Hour": ,
  "Demonflame": ,
  "Atomic": ,
  "Purple Energy": ,
  "Galactic Codex": ,
  "Death by Disco": ,
  "Something Burning This Way Comes": ,
  "Voltaic Hat Protector": ,
  "Subatomic": ,
  "Ancient Codex": ,
  "Ghastly Ghosts": ,
  "Death at Dusk": ,
  "Frostbite": ,
  "Green Energy": ,
  "Ether Trail": ,
  "Time Warp": ,
  "Cool": ,
  "Morning Glory": ,
  "Green Black Hole": ,
  "Magnetic Hat Protector": ,
  "Ghastly Ghosts Jr": ,
  "Nether Trail": ,
  "Amaranthine": ,
  "Circling Heart": ,
  "The Ooze": ,
  "Sulphurous": ,
  "Cauldron Bubbles": ,
  "Electric Hat Protector": ,
  "Eldritch Flame": ,
  "Stare From Beyond": ,
  "Ancient Eldritch": ,
  "Haunted Ghosts": ,
  "Haunted Phantasm Jr": ,
  "It's a mystery to everyone": ,
  "Haunted Phantasm": ,
  "Phosphorous": ,
  "It's a puzzle to me": ,
  "Flaming Lantern": ,
  "Hot": ,
  "Isotope": ,
  "Vivid Plasma": ,
  "Molten Mallard": ,
  "Tesla Coil": ,
  "Power Surge": ,
  "Holy Grail": ,
  "Electrostatic": ,
  "Starstorm Insomnia": ,
  "Disco Beat Down": ,
  "Searing Plasma": ,
  "Eerie Orbiting Fire": ,
  "Starstorm Slumber": ,
  "Cloud 9": ,
  "Circling Peace Sign": ,
  "Screaming Tiger": ,
  "Neutron Star": ,
  "Internal Smoke": ,
  "Circling TF Logo": ,
  "Hellish Inferno": ,
  "Purple Confetti": ,
  "Stormy Storm": ,
  "Spectral Swirl": ,
  "Blizzardy Storm": ,
  "Infernal Flames": ,
  "Showstopper": ,
  "Fountain of Delight": ,
  "Miami Nights": ,
  "Memory Leak": ,
  "Green Confetti": ,
  "'72": ,
  "Terror-Watt": ,
  "Orbiting-Fire": ,
  "Orbiting Planets": ,
  "Bubbling": ,
  "Steaming": ,
  "Smoking": ,
  "Massed Flies": ,
  "Kill-a-Watt": ,
  "Overclocked": ,
  "Dead Presidents": ,
  "Aces High": ,
  "Skill Gotten Gains": ,
  "Nuts n' Bolts": ,
  "Mega Strike": ,
  "Silver Cyclone": ,
  "Midnight Whirlwind": ,
}
